version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: pokemonreviewservice
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: pokemon_review_db
    ports:
      - "5432:5432"